name: Fullstack CI - React & Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # FRONTEND
      - name: Install frontend dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Test frontend (optional)
        run: |
          if [ -f "package.json" ]; then
            npm test || echo "No frontend tests found"
          fi

      # BACKEND
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Test backend (optional)
        working-directory: backend
        run: |
          if [ -f "package.json" ]; then
            npm test || echo "No backend tests found"
          fi
